FROM ubuntu:24.04

# prevent hangs due to tzdata setup
ENV TZ=Europe/London
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Install R, RStudio Desktop, D-Bus, and X11 dependencies
RUN apt-get update && apt-get install -y \
    wget \
    gnupg \
    dbus-x11 \
    libxtst6 \
    libx11-xcb1 \
    libgl1 \
    libqt5widgets5 \
    libqt5gui5 \
    libqt5core5a && \
    # various packages
    apt install -y --no-install-recommends software-properties-common dirmngr && \
    # Install R
    apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9 && \
    echo "deb https://cloud.r-project.org/bin/linux/ubuntu noble-cran40/" >> /etc/apt/sources.list && \
    apt-get update && apt-get install -y r-base r-base-dev r-recommended r-cran-systemfonts && \
    # packagees required to make rstudio run
    apt-get install -y wget libgbm1 libnss3 libasound2t64 && \
    # packages for single cell analysis
    apt install -y libxml2-dev libgsl-dev libudunits2-dev libgsl-dev \
        libudunits2-dev libfontconfig-dev libcairo2-dev libgdal-dev cmake \
        libpng-dev libtiff5-dev libjpeg-dev libharfbuzz-dev libfribidi-dev hdf5-tools libhdf5-dev && \
    # lib for ancombc2 - gnu multiple precision lib, for arb precision arithmetic, libgmp10 already loaded
    apt install -y libgmp-dev


# Install RStudio Desktop - current version of rstudio still at 'jammy' link
RUN wget https://download1.rstudio.org/electron/jammy/amd64/rstudio-2025.05.1-513-amd64.deb
RUN apt-get install -y ./rstudio-2025.05.1-513-amd64.deb
RUN rm ./rstudio-2025.05.1-513-amd64.deb
#RUN apt update --fix-missing # update the package list without errors due to missing deps
#RUN apt install -f # install missing packages

RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/*
RUN which rstudio

# Create a user matching the host UID/GID
#ARG UID=1000
#ARG GID=1000
#ARG USER=rstudio
#RUN groupadd -g ${GID} ${USER} && \
#    useradd -u ${UID} -g ${GID} -m -s /bin/bash ${USER}

# Create D-Bus system bus directory
RUN mkdir -p /var/run/dbus

# Start RStudio Desktop
CMD rstudio --no-sandbox #/init as a command does not work

